Application=Automation Exercise
Environment=QA
Browser=Chrome
Browser.Version=150
OS=Windows 10
Java.Version=17
Framework=Selenium Java
Build.Tool=Maven
Test.Framework=TestNG
Report=Allure
Automation.Engine=Selenium WebDriver